apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student
  strategy:
    type: Recreate
 #   minReadySeconds: 20
  template:
    metadata:
      name: studentapp-pod
      labels: 
        app: student
    spec:
      containers:
        - name: student-cont
          image: pankaj6262/student
          ports:
            - containerPort: 8080

---

apiVersion: v1 
kind: Service
metadata:
  name: student-service
spec:
  selector:
    app: student
  ports: 
    - port: 8080
      targetPort: 8080
  type: NodePort
